### ISSUE TITLE
NSArray method for concatenation ?

### ISSUE THREAD

**Issue by RobTrew** [dagware/DanThomas#1]
I guess a lazy (tho perhaps slower-executing ?) way of writing ConvertToMultiLineString() might also be:

``` applescript
use framework "Foundation"

on ConvertListToMultiLineString(theList)
    (current application's (NSArray's arrayWithObject:theList)'s ¬
        objectAtIndex:0)'s componentsJoinedByString:linefeed
end ConvertListToMultiLineString
```

**Comment by dagware** [comment]
Yeah, I don't really care. I'm just trying to get all my crap up on the web somewhere. I've got too much to do to care about the technical details of what's the best way of doing something. I only care that something _can_ be done right now. :)

Thanks for posting something, though. I wasn't sure if I had it set up to allow this kind of thing or not.

Now if only I could figure out a way to allow decent searching on the wiki...
